services:
  tb4m7q9x2v:
    container_name: tb4m7q9x2v_app
    image: ghcr.io/mr-devloper005/totebagus.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3077:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
